package com.test.configuration;

/**
 * @class Properties.java
 * @author Felipe
 * @Date Jun 16, 2013
 * @since 1.0
 */
public enum Properties {

	BALANCER_PORT, NODE_PORT, NODE_PORT2, NODE_1_IP, NODE_2_IP, LOGS_PATH, 
	QUEUE_EXECUTOR_IMPL, MESSAGE_PROCESSOR_IMPL, PACKET_SIZE, HASH_SIZE,
	EXECUTOR_POOL_SIZE, TEST_TIME, POOL_SIZE, LOAD_SIZE, LOAD_TIME, FRAMES_PATH, BALANCER_IP,
	HEARTBEAT_PORT, HEARTBEAT_PACKET_SIZE, MAX_REPONSE_TIME_NODE
}
